---
excluded:
- Pods
- build
included:
- ./
- ../Pod/
force_cast: warning
force_try: warning
opt_in_rules:
- force_unwrapping
- switch_case_on_newline
- first_where
- attributes
- closure_end_indentation
- closure_spacing
- empty_count
- explicit_init
- implicitly_unwrapped_optional
- overridden_super_call
- prohibited_super_call
- redundant_nil_coalescing
- private_outlet
line_length: 140
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
disabled_rules:
- todo
- block_based_kvo
