platform :ios, '15.0'
use_frameworks!

target 'RingPublishingGDPR-Example' do
  pod 'RingPublishingGDPR', :path => '../'
  pod 'SwiftLint'
end

# Temporary fix about warning for deployment target set by Cocoapods to iOS 8
# https://github.com/CocoaPods/CocoaPods/issues/9884
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
